---
- name: Converge
  hosts: all
  become: true

  tasks:

    - file:
        path: /run/test
        state: directory

    - name: "Include grycap.nfs"
      include_role:
        name: "ansible-role-nfs"
      vars:
        nfs_mode: 'front'
        nfs_exports: [{path: "/run/test", export: "localhost(fsid=0,rw,async,no_subtree_check,insecure)"}]


    - file:
        path: /tmp/test
        state: directory

    - name: "Include grycap.nfs"
      include_role:
        name: "ansible-role-nfs"
      vars:
        nfs_mode: 'wn'
        nfs_client_imports: [{ local: "/tmp/test", remote: "/", server_host: "localhost" }]


    - name: "Include grycap.nfs"
      include_role:
        name: "ansible-role-nfs"
      vars:
        nfs_only_v4: true
        nfs_mode: 'front'
        nfs_exports: [{path: "/run/test", export: "localhost(fsid=0,rw,async,no_subtree_check,insecure)"}]


    - name: "Include grycap.nfs"
      include_role:
        name: "ansible-role-nfs"
      vars:
        nfs_only_v4: true
        nfs_mode: 'wn'
        nfs_client_imports: [{ local: "/tmp/test", remote: "/", server_host: "localhost" }]